//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4E 5C 99 0C 0C 12 15 18 1F 1E 21 24 D8 D5 2D 30 8B 36 39 3C 3F 42 45 48 0B 4E 51 54 57 5A 5D 60 63 66 69 6C 6F 72 75 78 7B 7E 81 84 87 8A 8D 90 93 96 99 9C 9F A2 A5 A8 AB AE B1 B4 37 BA BD C0 CD D9 73 C2 CF 66 DC 15 FA 66 E0 A8 2A CB B9 98 9A 85 D9 8C 71 69 6E 7E 6E 7F 35 7B 7A 70 4F 4B 53 0A 4F 55 13 44 4C 52 1F 2B 2B 68 0F 01 02 74 3A 35 39 05 4D 6B 64 66 4B 72 75 78 7B 7E 81 84 D7 CF 8D 90 DF 97 9D 9C 0D 1A 42 F0 AB AE B1 B4 B7 BA BD C0 23 C6 C7 ED C4 D3 D3 D8 DB 1C E0 E4 E7 E2 ED F0 F3 F6 F9 FC 8D E7 08 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dummy {
            get {
                return ResourceManager.GetString("Dummy", resourceCulture);
            }
        }
    }
}
